spring:
  h2:
    console:
      enabled: true
  devtools:
    add-properties: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml 
